platform: linux

image_resource:
  type: docker-image
  source: 
    repository: openjdk
    tag: latest

inputs:
- name: spring-flight-school

run:
  path: chmod
  args: [+x, ./spring-flight-school/ci/test.sh]