platform: linux

image_resource:
  type: docker-image
  source: 
    repository: openjdk
    tag: latest

inputs:
- name: spring-flight-school

run:
  path: mvn
  args: ["-f", "spring-flight-school/pom.xml", "clean", "package"]