platform: linux

image_resource:
  type: docker-image
  source: 
    repository: maven
    tag: latest

inputs:
- name: spring-flight-school

outputs:
- name: built-jar

run:
  path: mvn
  args: ["-f", "spring-flight-school/pom.xml", "clean", "package"]