resources:
- name: spring-flight-school
  type: git
  source:
    uri: https://github.com/Lwiczyn/spring-flight-school
    branch: master

jobs:
- name: test-app
  plan:
  - get: spring-flight-school
    trigger: true
  - task: set-permissions
    file: spring-flight-school/set-permissions.yml
  - task: tests
    file: spring-flight-school/build.yml